-
  name: PB on ansible project
  hosts: node1
  tasks:
    - name: code to install apache web server
      yum:
        name: httpd
        state: present

    - name: code to startapache server
      service: 
        name: httpd
        state: started

    - name: code to enable apache at boot time
      service:
        name: httpd
        enabled: yes

    - name: code to create a directory at /opt
      file:
        path: /opt/apache-logs
        state: directory

    - name: code to create a file under logs directory
      file:
        path: /opt/apache-logs/apache-log.logs
        state: touch

    - name: code to write a message into log file
      lineinfile:
        dest: /opt/apache-logs/apache-log.logs
        line: 'Apache Web Server is successfully installed'

    - name: code to create index.html if does not exist
      file:
        path: /var/www/html/index.html
        state: touch

    - name: code to display a message on webpage
      lineinfile:
        dest: /var/www/html/index.html
        line: '<html>
               <body>
               <h1> THIS IS ANSIBLE PROJECT </h1>
               </body>
               </html>'   