-
  name: PB on use case of variable concept
  hosts: all
  vars:
    a: 10
    b: 35.5
    c: "DSDFGFGH909"
    d: "Welcome to India"
  tasks:
  - name: code  to create file
    file:
      path: /opt/variable.txt
      action: touch
  
  - name: code to write variable values into the file
    lineinfile:
      path: /opt/variable.txt
      line: 'The value of A is {{a}} B is {{b}} C is {{c}} D is {{d}}'
      create: yes
      

