-
  name: pb on use case of loops
  hosts: node2
  tasks:
   - name: below code for yum installations using loops
     yum:
      name: "{{ item }}"
      state: absent
     loop:
      - git
      - docker
      - net-tools
      - finger

